# Generated by Django 3.2.4 on 2021-08-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=15)),
                ('LName', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=30)),
                ('Ph_No', models.CharField(max_length=13)),
                ('EDate', models.DateField()),
            ],
            options={
                'db_table': 'Employee_Data',
            },
        ),
    ]
